'use client';

import { useState } from 'react';
import { Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { PILLAR_LABELS, type Pillar } from '@/lib/types';

interface GapResult {
  weakest_pillar?: string;
  summary?: string;
  pillars?: { pillar?: string; assessment?: string; suggestion?: string }[];
  before_lodging?: string[];
}

export function GapAnalysis() {
  const [result, setResult] = useState<GapResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function run() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/readiness', { method: 'POST' });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? 'Analysis failed.');
      setResult(json);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Analysis failed.');
    } finally {
      setLoading(false);
    }
  }

  const label = (p?: string) =>
    p && p in PILLAR_LABELS ? PILLAR_LABELS[p as Pillar] : p ?? '';

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-3">
          <div>
            <CardTitle className="text-base">Gap analysis</CardTitle>
            <p className="mt-1 text-sm text-muted-foreground">
              Where your evidence is thin, and what would strengthen it.
            </p>
          </div>
          <Button onClick={run} disabled={loading} size="sm" variant="outline">
            <Sparkles className="h-4 w-4" />
            {loading ? 'Analysing…' : result ? 'Re-run' : 'Analyse'}
          </Button>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {error && (
          <Alert variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {!result && !error && (
          <p className="text-sm text-muted-foreground">
            Thin evidence in any single pillar weakens the whole application. Run this to see
            which one needs work.
          </p>
        )}

        {result && (
          <div className="space-y-4 text-sm">
            {result.weakest_pillar && (
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-muted-foreground">Weakest pillar:</span>
                <Badge variant="warning">{label(result.weakest_pillar)}</Badge>
              </div>
            )}
            {result.summary && <p>{result.summary}</p>}

            {result.pillars && result.pillars.length > 0 && (
              <ul className="space-y-3">
                {result.pillars.map((p, i) => (
                  <li key={`${p.pillar}-${i}`} className="border-l-2 pl-3">
                    <p className="font-medium">{label(p.pillar)}</p>
                    {p.assessment && (
                      <p className="mt-0.5 text-muted-foreground">{p.assessment}</p>
                    )}
                    {p.suggestion && <p className="mt-1">{p.suggestion}</p>}
                  </li>
                ))}
              </ul>
            )}

            {result.before_lodging && result.before_lodging.length > 0 && (
              <div>
                <p className="font-medium">Before lodging</p>
                <ul className="mt-1 list-disc space-y-1 pl-5 text-muted-foreground">
                  {result.before_lodging.map((s, i) => (
                    <li key={i}>{s}</li>
                  ))}
                </ul>
              </div>
            )}

            <p className="text-xs text-muted-foreground">
              Generated by an AI model from the items in this tool. It is not migration
              advice and not an assessment by the Department.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
